<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of HtmlHelper
 *
 * @author OSCARITO
 */

class HtmlHelper {
   
    private function obtenerFecha(){
        $dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado");
        $meses = array("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");
        return  $dias[date('w')]." ".date('d')." de ".$meses[date('n')-1]. " del ".date('Y') ;
    } 

   public function  paginaPrimerSegmento($nombre,$oferta,$oferta_letra,$pago,$plazo,$folio,$comision,$comision_letra,$tasa_fija,$tasa_letra,$cat,$guid){
            $hoy=  $this->obtenerFecha();
            $html='';

            $html.= "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"viewport\" content=\"initial-scale=1.0\"><meta name=\"format-detection\" content=\"telephone=no\"><title>FINANCIERA AYUDAMOS</title><style type=\"text/css\">.socialLinks {font-size: 6px;}\n"; 
            $html.= ".socialLinks a {display: inline-block;}\n"; 
            $html.= ".socialIcon {display: inline-block;vertical-align: top;padding-bottom: 0px;border-radius: 100%;}\n"; 
            $html.= "table.vb-row.fullwidth {border-spacing: 0;padding: 0;}</style><style type=\"text/css\">\n"; 
            $html.= "    /* yahoo, hotmail */\n"; 
            $html.= "    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div{ line-height: 100%; }\n"; 
            $html.= "    .yshortcuts a{ border-bottom: none !important; }\n"; 
            $html.= "    .vb-outer{ min-width: 0 !important; }\n"; 
            $html.= "    .RMsgBdy, .ExternalClass{\n"; 
            $html.= "      width: 100%;\n"; 
            $html.= "      background-color: #3f3f3f;\n"; 
            $html.= "      background-color: #3f3f3f}\n"; 
            $html.= "\n"; 
            $html.= "    /* outlook */\n"; 
            $html.= "    table{ mso-table-rspace: 0pt; mso-table-lspace: 0pt; }\n"; 
            $html.= "    #outlook a{ padding: 0; }\n"; 
            $html.= "    img{ outline: none; text-decoration: none; border: none; -ms-interpolation-mode: bicubic; }\n"; 
            $html.= "    a img{ border: none; }\n"; 
            $html.= "    @media screen and (max-device-width: 900px), screen and (max-width: 900px) {\n"; 
            $html.= "  .mobile-full{\n"; 
            $html.= "        float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\n"; 
            $html.= "      }\n"; 
            $html.= "  	}\n"; 
            $html.= "    @media screen and (max-device-width: 600px), screen and (max-width: 600px) {\n"; 
            $html.= "  	}\n"; 
            $html.= "      table.vb-container, table.vb-row{\n"; 
            $html.= "        width: 95% !important;\n"; 
            $html.= "      }\n"; 
            $html.= "\n"; 
            $html.= "      .mobile-hide{ display: none !important; }\n"; 
            $html.= "      .mobile-textcenter{ text-align: center !important; }\n"; 
            $html.= "\n"; 
            $html.= "      .mobile-full{\n"; 
            $html.= "        float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\n"; 
            $html.= "      }\n"; 
            $html.= "      img.mobile-full{\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        height: auto !important;\n"; 
            $html.= "      }   \n"; 
            $html.= "    }\n"; 
            $html.= "  </style><style type=\"text/css\">#ko_doubleArticleBlock_21 .links-color a, #ko_doubleArticleBlock_21 .links-color a:link, #ko_doubleArticleBlock_21 .links-color a:visited, #ko_doubleArticleBlock_21 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_15 .links-color a, #ko_textBlock_15 .links-color a:link, #ko_textBlock_15 .links-color a:visited, #ko_textBlock_15 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_13 .links-color a:visited, #ko_textBlock_13 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_17 .links-color a, #ko_textBlock_17 .links-color a:link, #ko_textBlock_17 .links-color a:visited, #ko_textBlock_17 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_22 .links-color a, #ko_textBlock_22 .links-color a:link, #ko_textBlock_22 .links-color a:visited, #ko_textBlock_22 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_23 .links-color a, #ko_textBlock_23 .links-color a:link, #ko_textBlock_23 .links-color a:visited, #ko_textBlock_23 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_26 .links-color a, #ko_textBlock_26 .links-color a:link, #ko_textBlock_26 .links-color a:visited, #ko_textBlock_26 .links-color a:hover {color: #3f3f3f;color: #1a51c3;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_15 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_13 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_23 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_26 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_15 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_13 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_23 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_26 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_15 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_textBlock_13 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_textBlock_23 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_textBlock_26 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_sideArticleBlock_3 .links-color a, #ko_sideArticleBlock_3 .links-color a:link, #ko_sideArticleBlock_3 .links-color a:visited, #ko_sideArticleBlock_3 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .links-color a, #ko_sideArticleBlock_25 .links-color a:link, #ko_sideArticleBlock_25 .links-color a:visited, #ko_sideArticleBlock_25 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_footerBlock_2 .links-color a:visited, #ko_footerBlock_2 .links-color a:hover {color: #ccc;color: #ccc;text-decoration: underline;}\n"; 
            $html.= "#ko_imageBlock_12 a, #ko_imageBlock_12 a:link, #ko_imageBlock_12 a:visited, #ko_imageBlock_12 a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}</style></head><body style=\"margin: 0;padding: 0;background-color: #3f3f3f;color: #919191;\" alink=\"#cccccc\" bgcolor=\"#3f3f3f\" text=\"#919191\" vlink=\"#cccccc\">\n"; 
            $html.= "\n"; 
            $html.= "  <center>\n"; 
            $html.= "\n"; 
            $html.= "  <!-- preheaderBlock -->\n"; 
            $html.= "  \n"; 
            $html.= "\n"; 
            $html.= "  <!-- /preheaderBlock --><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_sideArticleBlock_3\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-row fullpad\" style=\"border-collapse: separate;border-spacing: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td class=\"mobile-row\" style=\"font-size: 0;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"552\"><tr><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"368\">\n"; 
            $html.= "<![endif]--><div style=\"display: inline-block; max-width: 368px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"368\"><tbody><tr><td style=\"font-size: 18px; font-family: Arial, Helvetica, sans-serif; color: #3f3f3f; text-align: left;\">\n"; 
            $html.= "                          <span style=\"color: #3f3f3f;\">$hoy</span>\n"; 
            $html.= "                        </td>\n"; 
            $html.= "                      </tr><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important; padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div><!--[if (gte mso 9)|(lte ie 8)]></td>\n"; 
            $html.= "<![endif]--><!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"184\" style=\"; \">\n"; 
            $html.= "<![endif]--><div style=\"display: inline-block; max-width: 184px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"184\"><tbody><tr><td class=\"links-color\" align=\"left\" valign=\"top\" width=\"100%\">\n"; 
            $html.= "                          \n"; 
            $html.= "                            <img class=\"\" alt=\"\" style=\"border: 0px;display: block;vertical-align: top;width: 100%;height: auto;max-width: 166px;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;\" src=\"http://siaisa-emailing.sistema-siaisa.net/img/logo-financiera.png\" border=\"0\" hspace=\"0\" vspace=\"0\" width=\"166\"></td>\n"; 
            $html.= "                      </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></tr></table><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_15\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><h3>Estimado (a):$nombre</h3></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_titleBlock_10\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container halfpad\" style=\"border-collapse: separate;border-spacing: 9px;padding-left: 9px;padding-right: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"background-color: #ffffff;font-size: 22px;font-family: Arial, Helvetica, sans-serif;color: #1c3a61;text-align: center;font-weight: bold;\" align=\"center\" bgcolor=\"#ffffff\">\n"; 
            $html.= "              <span>Por ser cliente BBVA Bancomer,  te AYUDAMOS con el REGRESO A CLASES  con un crédito <span style=\"color: #f79646;\"> Precalificado</span> hasta por <span style=\"color: #f79646;\">$$oferta </span> no deje pasar esta oportunidad</span>\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "<table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_13\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_17\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-top: 0px;text-align: center;\" data-mce-style=\"text-align: center;\">($oferta_letra. 00/00 Moneda Nacional)</p><p style=\"margin: 1em 0px;margin-bottom: 0px;text-align: center;\" data-mce-style=\"text-align: center;\">Usted pagará  <b>$$pago</b> por Quincena por <b>$plazo</b> Quincenas</p></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_imageBlock_12\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;min-width: 0 !important;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullwidth\" style=\"border-collapse: separate;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"center\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"570\"><tbody><tr><td align=\"center\" valign=\"top\">\n"; 
            $html.= "              <img class=\"mobile-full\" alt=\"\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important; border: 0px;border-radius: 0px;display: block;max-width: 570px;width: 100%;height: auto;font-size: 16px;font-family: Arial,Helvetica,sans-serif;color: #17365d;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;\" src=\"http://siaisa-emailing.sistema-siaisa.net/img/familia.png\" border=\"0\" hspace=\"0\" vspace=\"0\" width=\"570\"></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_titleBlock_10\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container halfpad\" style=\"border-collapse: separate;border-spacing: 9px;padding-left: 9px;padding-right: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"background-color: #ffffff; font-size: 22px; font-family: Arial, Helvetica, sans-serif; color: #f79646; text-align: center;\" align=\"center\" bgcolor=\"#ffffff\">\n"; 
            $html.= "              <span>Solicítalo hoy mismo, da clic en Sí me Interesa, completa el Formulario y nosotros te llamamos</span>\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_titleBlock_11\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container halfpad\" style=\"border-collapse: separate;border-spacing: 9px;padding-left: 9px;padding-right: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"background-color: #ffffff; font-size: 22px; font-family: Arial, Helvetica, sans-serif; color: #17365d; text-align: center;\" align=\"center\" bgcolor=\"#ffffff\">\n"; 
            $html.= "              <span>Tu Folio es: $folio</span>\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_doubleArticleBlock_21\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-row fullpad\" style=\"border-collapse: separate;border-spacing: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"font-size: 0;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"552\"><tr><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><td align=\"left\" valign=\"top\" width=\"276\"><![endif]--> \n"; 
            $html.= "<div style=\"display: inline-block; max-width: 276px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\" class=\"mobile-full\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"276\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table class=\"mobile-full\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td style=\"font-size: 13px; font-family: Arial, Helvetica, sans-serif; text-align: center; color: #ffffff; font-weight: normal; padding-left: 18px; padding-right: 18px; background-color: #f79646; border-radius: 4px;\" align=\"center\" bgcolor=\"#bfbfbf\" height=\"26\" valign=\"middle\" width=\"auto\">\n"; 
            $html.= "                                 <a style=\"text-decoration: none; color: #ffffff; font-weight: normal;\" target=\"_new\" href=\"http://promocionesfinancieraayudamos.com/registro/?guid=$guid\">ME INTERESA</a>\n"; 
            $html.= "                              </td>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div><!--[if (gte mso 9)|(lte ie 8)]></td>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"276\">\n"; 
            $html.= "<![endif]--><div style=\"display: inline-block; max-width: 276px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\" class=\"mobile-full\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"276\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table class=\"mobile-full\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td style=\"font-size: 13px; font-family: Arial, Helvetica, sans-serif; text-align: center; color: #3f3f3f; font-weight: normal; padding-left: 18px; padding-right: 18px; background-color: #f79646; border-radius: 4px;\" align=\"center\" bgcolor=\"#bfbfbf\" height=\"26\" valign=\"middle\" width=\"auto\">\n"; 
            $html.= "                                <a style=\"text-decoration: none; color: #ffffff; font-weight: normal;\" target=\"_new\" href=\"http://promocionesfinancieraayudamos.com/no-interesado/?guid=$guid\">NO ME INTERESA</a>\n"; 
            $html.= "                              </td>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div>\n"; 
                        $html.= "<![endif]--><div style=\"display: inline-block; max-width: 276px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\" class=\"mobile-full\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"276\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table class=\"mobile-full\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td style=\"font-size: 13px; font-family: Arial, Helvetica, sans-serif; text-align: center; color: #3f3f3f; font-weight: normal; padding-left: 18px; padding-right: 18px; background-color: #00548d; border-radius: 4px;\" align=\"center\" bgcolor=\"#bfbfbf\" height=\"26\" valign=\"middle\" width=\"auto\">\n"; 
            $html.= "                                <a style=\"text-decoration: none; color: #ffffff; font-weight: normal;\" target=\"_new\" href=\"http://chat.promocionesfinancieraayudamos.com/\">Cualquier duda chatea con nosotros ¡click aquí!</a>\n"; 
            $html.= "                              </td>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></tr></table><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_22\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-top: 0px;text-align: center;\" data-mce-style=\"text-align: center;\"><span style=\"color: rgb(230, 108, 21);\" data-mce-style=\"color: #e66c15;\">¡Pagos fijos, Sin Aval ni Garantías!</span></p><p style=\"margin: 1em 0px;margin-bottom: 0px;text-align: center;line-height: 2em;\" data-mce-style=\"text-align: center; line-height: 2em;\"><strong>Promoción vigente hasta el 30/Septiembre/2016</strong></p></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
           
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_23\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><h6 style=\"text-align: center;\" data-mce-style=\"text-align: center;\"><strong style=\" color:#f79646;\">Financiera Ayudamos S.A. de C.V. SOFOM ER,</strong>&nbsp; forma parte de<br> BBVA Bancomer S.A. de C.V. Institución de Banca Múltiple Grupo Financiero BBVA Bancomer</h6></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_sideArticleBlock_25\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 570px !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px; \">\n"; 
            $html.= "        <table class=\"vb-row fullpad\" style=\"border-collapse: separate;border-spacing: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td class=\"mobile-row\" style=\"font-size: 0;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"552\"><tr><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"368\">\n"; 
            $html.= "<![endif]--><div class=\"mobile-full\" style=\"display: inline-block; max-width: 368px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-outer\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width:0 !important;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"368\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 12px; font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0); margin-bottom:5px; margin-top:5px; margin-bottom:5px;margin-top:0px; display:inline;\" align=\"left\"><p style=\"/* margin-top: 10px; */margin-bottom: 5px;/* margin: 1em 0px; */\"><b>CAT: $cat%</b>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "<small style=\" color: rgb(87, 83, 83); margin-top: 0px; margin-bottom: 5px; color:#757272;\">Sin IVA. Informativo. Fecha de cálculo: 26 de agosto del 2016 </small></p>\n"; 
            $html.= "<small style=\"\n"; 
            $html.= "    margin-top: 0px;  color:#757272;\n"; 
            $html.= "    margin-bottom: 0px;\n"; 
            $html.= "\">Vigencia para contratar el crédito del Viernes 02 de Septiembre del 2016 al 30 de septiembre de 2016</small>\n"; 
            $html.= "<br><small style=\"margin-top: 5px;margin-bottom: 5px; color:#757272; \">Comisión por apertura:$comision% ($comision_letra)</small><br><small style=\"\n"; 
            $html.= "    margin-top: 5px;"; 
            $html.= "    margin-bottom: 5px; color:#757272; "; 
            $html.= "\">Tasa fija: $tasa_fija% anual ($tasa_letra)</small>\n"; 
            $html.= "<br><small style=\"\n"; 
            $html.= "    margin-top: 5px;  color:#757272;\n"; 
            $html.= "    margin-bottom: 5px;\n"; 
            $html.= "\">Moneda Nacional ( Pesos mexicanos)</small>\n"; 
            $html.= "<br><small style=\" margin-top: 5px; color:#757272; margin-bottom: 5px;\">*Aplican restricciones. Sujeto a evaluación de crédito.</small></td>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "                      </tr>\n"; 
            $html.= "                      </tbody></table></div><!--[if (gte mso 9)|(lte ie 8)]></td>\n"; 
            $html.= "<![endif]--><!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"184\" style=\"; \">\n"; 
            $html.= "<![endif]--><div class=\"mobile-full\" style=\"display: inline-block; max-width: 184px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-outer\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"184\"><tbody>\n"; 
            $html.= "                      </tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></tr></table><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_26\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; color:  rgb(87, 83, 83);\" align=\"left\"><small style=\"text-align: center; color:#757272 \" data-mce-style=\"text-align: center;\">Financiera\n"; 
            $html.= " Ayudamos, S.A. de C.V. SOFOM ER, Av. Canal de Miramontes 2600, Colonia \n"; 
            $html.= "Avante,&nbsp; Delegación&nbsp; Coyoacán, 04460, DF, &nbsp;recaba sus \n"; 
            $html.= "datos para verificar su identidad. <br> El Aviso de Privacidad Integral \n"; 
            $html.= "actualizado se encuentra a su disposición en cualquiera&nbsp; de \n"; 
            $html.= "nuestras sucursales y en la página <a href=\"http://www.financiera-ayudamos.mx/\" style=\"color: #1a51c3;text-decoration: underline;\">http://www.financiera-ayudamos.mx</a>. <br></small><small style=\"color:#757272\">Consulta los requisitos de contratación, términos y condiciones en: <a href=\"http://www.financiera-ayudamos.mx/\" style=\"color: #1a51c3;text-decoration: underline;\">http://www.financiera-ayudamos.mx</a></h6></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><!-- footerBlock --><!-- /footerBlock --></center>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "</body></html>\n";



            return $html;
     }
   
   public  function paginaMensajeFinanciera($mensaje){
            $mensaje=  utf8_decode($mensaje);
            $html="";
            $html.= "<html>\n"; 
            $html.= "    <head>\n"; 
            $html.= "    <meta charset=\"utf-8\">\n"; 
            $html.= "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n"; 
            $html.= "    <title>REGISTRO COMPLETO</title>\n"; 
            $html.= "    <meta name=\"description\" content=\"\">\n"; 
            $html.= "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
            $html.= "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css\">\n"; 
            $html.= "    <link href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\" rel=\"stylesheet\">\n"; 
            $html.= "    <link rel=\"stylesheet\" href=\"../css/bootflat.min.css\">\n"; 
            $html.= "    <link rel=\"stylesheet\" href=\"../css/main_menu.css\">\n"; 
            $html.= "    <link rel=\"stylesheet\" href=\"../css/registro-completo.css\">\n"; 
            $html.= "    <link rel=\"stylesheet\" href=\"../css/animate.css\">\n"; 
            $html.= "    <script src=\"../js/vendor/modernizr-2.8.3-respond-1.4.2.min.js\"></script>\n"; 
            $html.= "    </head>\n"; 
            $html.= "\n"; 
            $html.= "    <body>\n"; 
            $html.= "        <div class=\"container\">\n"; 
            $html.= "           \n"; 
            $html.= "              <div class=\"col-md-12\">\n"; 
            $html.= "                <img class=\"img-responsive pull-left animated fadeIn\" src=\"https://mosaico.io/srv/f-9nkj8h3/img?src=https%3A%2F%2Fmosaico.io%2Ffiles%2F9nkj8h3%2Flogo.png&amp;method=resize&amp;params=166%2Cnull\">\n"; 
            $html.= "            </div>\n"; 
            $html.= "            <!--DIV AL CENTRO HORIZONTAL Y VERTICALMENTE-->\n"; 
            $html.= "            <center>\n"; 
            $html.= "                <div id=\"container\">\n"; 
            $html.= "                    <h1 class=\"md-title azul-financiera animated fadeInDownBig\"> \n"; 
            $html.= "                        $mensaje \n"; 
            $html.= "                    </h1>\n"; 
            $html.= "              </div>\n"; 
            $html.= "            </center>\n"; 
            $html.= "       \n"; 
            $html.= "          \n"; 
            $html.= "        </div>\n"; 
            $html.= "        \n"; 
            $html.= "    </body>\n"; 
            $html.= "</html>\n"; 
            $html.= "\n";
            return $html;
     }
      public function  paginaPrimerSegmento2($nombre,$oferta,$oferta_letra,$pago,$plazo,$folio,$comision,$comision_letra,$tasa_fija,$tasa_letra,$cat,$guid){
            $hoy=  $this->obtenerFecha();
            $html='';

            $html.= "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"viewport\" content=\"initial-scale=1.0\"><meta name=\"format-detection\" content=\"telephone=no\"><title>FINANCIERA AYUDAMOS</title><style type=\"text/css\">.socialLinks {font-size: 6px;}\n"; 
            $html.= ".socialLinks a {display: inline-block;}\n"; 
            $html.= ".socialIcon {display: inline-block;vertical-align: top;padding-bottom: 0px;border-radius: 100%;}\n"; 
            $html.= "table.vb-row.fullwidth {border-spacing: 0;padding: 0;}</style><style type=\"text/css\">\n"; 
            $html.= "    /* yahoo, hotmail */\n"; 
            $html.= "    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div{ line-height: 100%; }\n"; 
            $html.= "    .yshortcuts a{ border-bottom: none !important; }\n"; 
            $html.= "    .vb-outer{ min-width: 0 !important; }\n"; 
            $html.= "    .RMsgBdy, .ExternalClass{\n"; 
            $html.= "      width: 100%;\n"; 
            $html.= "      background-color: #3f3f3f;\n"; 
            $html.= "      background-color: #3f3f3f}\n"; 
            $html.= "\n"; 
            $html.= "    /* outlook */\n"; 
            $html.= "    table{ mso-table-rspace: 0pt; mso-table-lspace: 0pt; }\n"; 
            $html.= "    #outlook a{ padding: 0; }\n"; 
            $html.= "    img{ outline: none; text-decoration: none; border: none; -ms-interpolation-mode: bicubic; }\n"; 
            $html.= "    a img{ border: none; }\n"; 
            $html.= "    @media screen and (max-device-width: 900px), screen and (max-width: 900px) {\n"; 
            $html.= "  .mobile-full{\n"; 
            $html.= "        float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\n"; 
            $html.= "      }\n"; 
            $html.= "   }\n"; 
            $html.= "    @media screen and (max-device-width: 600px), screen and (max-width: 600px) {\n"; 
            $html.= "   }\n"; 
            $html.= "      table.vb-container, table.vb-row{\n"; 
            $html.= "        width: 95% !important;\n"; 
            $html.= "      }\n"; 
            $html.= "\n"; 
            $html.= "      .mobile-hide{ display: none !important; }\n"; 
            $html.= "      .mobile-textcenter{ text-align: center !important; }\n"; 
            $html.= "\n"; 
            $html.= "      .mobile-full{\n"; 
            $html.= "        float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\n"; 
            $html.= "      }\n"; 
            $html.= "      img.mobile-full{\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        height: auto !important;\n"; 
            $html.= "      }   \n"; 
            $html.= "    }\n"; 
            $html.= "  </style><style type=\"text/css\">#ko_doubleArticleBlock_21 .links-color a, #ko_doubleArticleBlock_21 .links-color a:link, #ko_doubleArticleBlock_21 .links-color a:visited, #ko_doubleArticleBlock_21 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_15 .links-color a, #ko_textBlock_15 .links-color a:link, #ko_textBlock_15 .links-color a:visited, #ko_textBlock_15 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_13 .links-color a:visited, #ko_textBlock_13 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_17 .links-color a, #ko_textBlock_17 .links-color a:link, #ko_textBlock_17 .links-color a:visited, #ko_textBlock_17 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_22 .links-color a, #ko_textBlock_22 .links-color a:link, #ko_textBlock_22 .links-color a:visited, #ko_textBlock_22 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_23 .links-color a, #ko_textBlock_23 .links-color a:link, #ko_textBlock_23 .links-color a:visited, #ko_textBlock_23 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_26 .links-color a, #ko_textBlock_26 .links-color a:link, #ko_textBlock_26 .links-color a:visited, #ko_textBlock_26 .links-color a:hover {color: #3f3f3f;color: #1a51c3;text-decoration: underline;}\n"; 
            $html.= "#ko_textBlock_15 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_13 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_23 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_26 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_textBlock_15 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_13 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_23 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_26 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_textBlock_15 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_textBlock_13 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_textBlock_23 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_textBlock_26 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_sideArticleBlock_3 .links-color a, #ko_sideArticleBlock_3 .links-color a:link, #ko_sideArticleBlock_3 .links-color a:visited, #ko_sideArticleBlock_3 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .links-color a, #ko_sideArticleBlock_25 .links-color a:link, #ko_sideArticleBlock_25 .links-color a:visited, #ko_sideArticleBlock_25 .links-color a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .long-text p {margin: 1em 0px;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .long-text p:last-child {margin-bottom: 0px;}\n"; 
            $html.= "#ko_sideArticleBlock_25 .long-text p:first-child {margin-top: 0px;}\n"; 
            $html.= "#ko_footerBlock_2 .links-color a:visited, #ko_footerBlock_2 .links-color a:hover {color: #ccc;color: #ccc;text-decoration: underline;}\n"; 
            $html.= "#ko_imageBlock_12 a, #ko_imageBlock_12 a:link, #ko_imageBlock_12 a:visited, #ko_imageBlock_12 a:hover {color: #3f3f3f;color: #f79646;text-decoration: underline;}</style></head><body style=\"margin: 0;padding: 0;background-color: #3f3f3f;color: #919191;\" alink=\"#cccccc\" bgcolor=\"#3f3f3f\" text=\"#919191\" vlink=\"#cccccc\">\n"; 
            $html.= "\n"; 
            $html.= "  <center>\n"; 
            $html.= "\n"; 
            $html.= "  <!-- preheaderBlock -->\n"; 
            $html.= "  \n"; 
            $html.= "\n"; 
            $html.= "  <!-- /preheaderBlock --><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_sideArticleBlock_3\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-row fullpad\" style=\"border-collapse: separate;border-spacing: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td class=\"mobile-row\" style=\"font-size: 0;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"552\"><tr><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"368\">\n"; 
            $html.= "<![endif]--><div style=\"display: inline-block; max-width: 368px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"368\"><tbody><tr><td style=\"font-size: 18px; font-family: Arial, Helvetica, sans-serif; color: #3f3f3f; text-align: left;\">\n"; 
            $html.= "                          <span style=\"color: #3f3f3f;\">$hoy</span>\n"; 
            $html.= "                        </td>\n"; 
            $html.= "                      </tr><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important; padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div><!--[if (gte mso 9)|(lte ie 8)]></td>\n"; 
            $html.= "<![endif]--><!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"184\" style=\"; \">\n"; 
            $html.= "<![endif]--><div style=\"display: inline-block; max-width: 184px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"184\"><tbody><tr><td class=\"links-color\" align=\"left\" valign=\"top\" width=\"100%\">\n"; 
            $html.= "                          \n"; 
            $html.= "                            <img class=\"\" alt=\"\" style=\"border: 0px;display: block;vertical-align: top;width: 100%;height: auto;max-width: 166px;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;\" src=\"http://siaisa-emailing.sistema-siaisa.net/img/logo-financiera.png\" border=\"0\" hspace=\"0\" vspace=\"0\" width=\"166\"></td>\n"; 
            $html.= "                      </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></tr></table><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_15\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><h3>Estimado (a):$nombre</h3></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_titleBlock_10\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container halfpad\" style=\"border-collapse: separate;border-spacing: 9px;padding-left: 9px;padding-right: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"background-color: #ffffff;font-size: 22px;font-family: Arial, Helvetica, sans-serif;color: #1c3a61;text-align: center;font-weight: bold;\" align=\"center\" bgcolor=\"#ffffff\">\n"; 
            $html.= "              <span>Por ser cliente BBVA Bancomer,  Hoy tienes <span style=\"color: #f79646;\"> Precalificado</span>un crédito hasta por:<span style=\"color: #f79646;\">$$oferta </span> no deje pasar esta oportunidad</span>\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "<table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_13\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_17\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-top: 0px;text-align: center;\" data-mce-style=\"text-align: center;\">($oferta_letra. 00/00 Moneda Nacional)</p><p style=\"margin: 1em 0px;margin-bottom: 0px;text-align: center;\" data-mce-style=\"text-align: center;\">Usted pagará  <b>$$pago</b> por Quincena por <b>$plazo</b> Quincenas</p></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_imageBlock_12\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;min-width: 0 !important;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullwidth\" style=\"border-collapse: separate;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"center\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"570\"><tbody><tr><td align=\"center\" valign=\"top\">\n"; 
            $html.= "              <img class=\"mobile-full\" alt=\"\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important; border: 0px;border-radius: 0px;display: block;max-width: 570px;width: 100%;height: auto;font-size: 16px;font-family: Arial,Helvetica,sans-serif;color: #17365d;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;\" src=\"http://siaisa-emailing.sistema-siaisa.net/img/familia.png\" border=\"0\" hspace=\"0\" vspace=\"0\" width=\"570\"></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_titleBlock_10\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container halfpad\" style=\"border-collapse: separate;border-spacing: 9px;padding-left: 9px;padding-right: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"background-color: #ffffff; font-size: 22px; font-family: Arial, Helvetica, sans-serif; color: #f79646; text-align: center;\" align=\"center\" bgcolor=\"#ffffff\">\n"; 
            $html.= "              <span>Solicítalo hoy mismo, da clic en Sí me Interesa, completa el Formulario y nosotros te llamamos</span>\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_titleBlock_11\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container halfpad\" style=\"border-collapse: separate;border-spacing: 9px;padding-left: 9px;padding-right: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"background-color: #ffffff; font-size: 22px; font-family: Arial, Helvetica, sans-serif; color: #17365d; text-align: center;\" align=\"center\" bgcolor=\"#ffffff\">\n"; 
            $html.= "              <span>Tu Folio es: $folio</span>\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_doubleArticleBlock_21\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-row fullpad\" style=\"border-collapse: separate;border-spacing: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td style=\"font-size: 0;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"552\"><tr><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><td align=\"left\" valign=\"top\" width=\"276\"><![endif]--> \n"; 
            $html.= "<div style=\"display: inline-block; max-width: 276px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\" class=\"mobile-full\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"276\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table class=\"mobile-full\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td style=\"font-size: 13px; font-family: Arial, Helvetica, sans-serif; text-align: center; color: #ffffff; font-weight: normal; padding-left: 18px; padding-right: 18px; background-color: #f79646; border-radius: 4px;\" align=\"center\" bgcolor=\"#bfbfbf\" height=\"26\" valign=\"middle\" width=\"auto\">\n"; 
            $html.= "                                 <a style=\"text-decoration: none; color: #ffffff; font-weight: normal;\" target=\"_new\" href=\"http://promocionesfinancieraayudamos.com/registro/?guid=$guid\">ME INTERESA</a>\n"; 
            $html.= "                              </td>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div><!--[if (gte mso 9)|(lte ie 8)]></td>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"276\">\n"; 
            $html.= "<![endif]--><div style=\"display: inline-block; max-width: 276px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\" class=\"mobile-full\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"276\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table class=\"mobile-full\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td style=\"font-size: 13px; font-family: Arial, Helvetica, sans-serif; text-align: center; color: #3f3f3f; font-weight: normal; padding-left: 18px; padding-right: 18px; background-color: #f79646; border-radius: 4px;\" align=\"center\" bgcolor=\"#bfbfbf\" height=\"26\" valign=\"middle\" width=\"auto\">\n"; 
            $html.= "                                <a style=\"text-decoration: none; color: #ffffff; font-weight: normal;\" target=\"_new\" href=\"http://promocionesfinancieraayudamos.com/no-interesado/?guid=$guid\">NO ME INTERESA</a>\n"; 
            $html.= "                              </td>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div>\n"; 
                        $html.= "<![endif]--><div style=\"display: inline-block; max-width: 276px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\" class=\"mobile-full\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-content\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"276\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-bottom: 0px;margin-top: 0px;\"><br></p></td>\n"; 
            $html.= "                      </tr><tr><td valign=\"top\">\n"; 
            $html.= "                          <table class=\"mobile-full\" style=\" float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;padding-top: 4px;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td style=\"font-size: 13px; font-family: Arial, Helvetica, sans-serif; text-align: center; color: #3f3f3f; font-weight: normal; padding-left: 18px; padding-right: 18px; background-color: #f79646; border-radius: 4px;\" align=\"center\" bgcolor=\"#bfbfbf\" height=\"26\" valign=\"middle\" width=\"auto\">\n"; 
            $html.= "                                <a style=\"text-decoration: none; color: #ffffff; font-weight: normal;\" target=\"_new\" href=\"http://chat.promocionesfinancieraayudamos.com/\">Cualquier duda chatea con nosotros, ¡click aquí!</a>\n"; 
            $html.= "                              </td>\n"; 
            $html.= "                            </tr></tbody></table></td>\n"; 
            $html.= "                      </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></tr></table><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_22\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><p style=\"margin: 1em 0px;margin-top: 0px;text-align: center;\" data-mce-style=\"text-align: center;\"><span style=\"color: rgb(230, 108, 21);\" data-mce-style=\"color: #e66c15;\">¡Pagos fijos, Sin Aval ni Garantías!</span></p><p style=\"margin: 1em 0px;margin-bottom: 0px;text-align: center;line-height: 2em;\" data-mce-style=\"text-align: center; line-height: 2em;\"><strong>Promoción vigente hasta el 30/Septiembre/2016</strong></p></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
           
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_23\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; font-family: Arial, Helvetica, sans-serif; color: #17365d;\" align=\"left\"><h6 style=\"text-align: center;\" data-mce-style=\"text-align: center;\"><strong style=\" color:#f79646;\">Financiera Ayudamos S.A. de C.V. SOFOM ER,</strong>&nbsp; forma parte de<br> BBVA Bancomer S.A. de C.V. Institución de Banca Múltiple Grupo Financiero BBVA Bancomer</h6></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_sideArticleBlock_25\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 570px !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px; \">\n"; 
            $html.= "        <table class=\"vb-row fullpad\" style=\"border-collapse: separate;border-spacing: 9px;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"570\"><tbody><tr><td class=\"mobile-row\" style=\"font-size: 0;\" align=\"center\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"552\"><tr><![endif]-->\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"368\">\n"; 
            $html.= "<![endif]--><div class=\"mobile-full\" style=\"display: inline-block; max-width: 368px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-outer\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width:0 !important;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"368\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 12px; font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0); margin-bottom:5px; margin-top:5px; margin-bottom:5px;margin-top:0px; display:inline;\" align=\"left\"><p style=\"/* margin-top: 10px; */margin-bottom: 5px;/* margin: 1em 0px; */\"><b>CAT: $cat%</b>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "<small style=\" color: rgb(87, 83, 83); margin-top: 0px; margin-bottom: 5px; color:#757272;\">Sin IVA. Informativo. Fecha de cálculo: 26 de agosto del 2016 </small></p>\n"; 
            $html.= "<small style=\"\n"; 
            $html.= "    margin-top: 0px;  color:#757272;\n"; 
            $html.= "    margin-bottom: 0px;\n"; 
            $html.= "\">Vigencia para contratar el crédito del Viernes 02 de Septiembre del 2016 al 30 de septiembre de 2016</small>\n"; 
            $html.= "<br><small style=\"margin-top: 5px;margin-bottom: 5px; color:#757272; \">Comisión por apertura:$comision% ($comision_letra)</small><br><small style=\"\n"; 
            $html.= "    margin-top: 5px;"; 
            $html.= "    margin-bottom: 5px; color:#757272; "; 
            $html.= "\">Tasa fija: $tasa_fija% anual ($tasa_letra)</small>\n"; 
            $html.= "<br><small style=\"\n"; 
            $html.= "    margin-top: 5px;  color:#757272;\n"; 
            $html.= "    margin-bottom: 5px;\n"; 
            $html.= "\">Moneda Nacional ( Pesos mexicanos)</small>\n"; 
            $html.= "<br><small style=\" margin-top: 5px; color:#757272; margin-bottom: 5px;\">*Aplican restricciones. Sujeto a evaluación de crédito.</small></td>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "                      </tr>\n"; 
            $html.= "                      </tbody></table></div><!--[if (gte mso 9)|(lte ie 8)]></td>\n"; 
            $html.= "<![endif]--><!--[if (gte mso 9)|(lte ie 8)]>\n"; 
            $html.= "<td align=\"left\" valign=\"top\" width=\"184\" style=\"; \">\n"; 
            $html.= "<![endif]--><div class=\"mobile-full\" style=\"display: inline-block; max-width: 184px; vertical-align: top; width: 100%; float: none !important;\n"; 
            $html.= "        width: 100% !important;\n"; 
            $html.= "        max-width: none !important;\n"; 
            $html.= "        padding-right: 0 !important;\n"; 
            $html.= "        padding-left: 0 !important;\"> \n"; 
            $html.= "\n"; 
            $html.= "                    <table class=\"vb-outer\" style=\"border-collapse: separate;width: 100%;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" align=\"left\" border=\"0\" cellpadding=\"0\" cellspacing=\"9\" width=\"184\"><tbody>\n"; 
            $html.= "                      </tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></tr></table><![endif]-->\n"; 
            $html.= "\n"; 
            $html.= "            </td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><table class=\"vb-outer\" style=\"background-color: #bfbfbf;mso-table-rspace: 0pt;mso-table-lspace: 0pt;min-width: 0 !important;\" id=\"ko_textBlock_26\" bgcolor=\"#bfbfbf\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tbody><tr><td class=\"vb-outer\" style=\"padding-left: 9px;padding-right: 9px;background-color: #bfbfbf;min-width: 0 !important;\" align=\"center\" bgcolor=\"#bfbfbf\" valign=\"top\">\n"; 
            $html.= "\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]><table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"570\"><tr><td align=\"center\" valign=\"top\"><![endif]-->\n"; 
            $html.= "        <div class=\"oldwebkit\" style=\"max-width: 570px;\">\n"; 
            $html.= "        <table class=\"vb-container fullpad\" style=\"border-collapse: separate;border-spacing: 18px;padding-left: 0;padding-right: 0;width: 100%;max-width: 570px;background-color: #fff;mso-table-rspace: 0pt;mso-table-lspace: 0pt;\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"18\" width=\"570\"><tbody><tr><td class=\"long-text links-color\" style=\"text-align: left; font-size: 16px; color:  rgb(87, 83, 83);\" align=\"left\"><small style=\"text-align: center; color:#757272 \" data-mce-style=\"text-align: center;\">Financiera\n"; 
            $html.= " Ayudamos, S.A. de C.V. SOFOM ER, Av. Canal de Miramontes 2600, Colonia \n"; 
            $html.= "Avante,&nbsp; Delegación&nbsp; Coyoacán, 04460, DF, &nbsp;recaba sus \n"; 
            $html.= "datos para verificar su identidad. <br> El Aviso de Privacidad Integral \n"; 
            $html.= "actualizado se encuentra a su disposición en cualquiera&nbsp; de \n"; 
            $html.= "nuestras sucursales y en la página <a href=\"http://www.financiera-ayudamos.mx/\" style=\"color: #1a51c3;text-decoration: underline;\">http://www.financiera-ayudamos.mx</a>. <br></small><small style=\"color:#757272\">Consulta los requisitos de contratación, términos y condiciones en: <a href=\"http://www.financiera-ayudamos.mx/\" style=\"color: #1a51c3;text-decoration: underline;\">http://www.financiera-ayudamos.mx</a></h6></td>\n"; 
            $html.= "          </tr></tbody></table></div>\n"; 
            $html.= "<!--[if (gte mso 9)|(lte ie 8)]></td></tr></table><![endif]-->\n"; 
            $html.= "      </td>\n"; 
            $html.= "    </tr></tbody></table><!-- footerBlock --><!-- /footerBlock --></center>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "</body></html>\n";



            return $html;
     }
   
}
