<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of EmailModel
 *
 * @author Victor Ortiz
 */
class EmailModel {
     private $connexion;
     private $host;
     private $dbName;
     private $user;
     private $password;
     
     public  function getConexion(){
       
         try{
                         $this->dbName="sistem80_emailing";
                         $this->user="sistem80_siaisa";
                         $this->password="director1210";
                         $this->host="sistema-siaisa.net";
                         $this->connexion= new PDO("mysql:host=".$this->host.";dbname=".$this->dbName,$this->user,$this->password);
                         $this->connexion->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
                         return $this->connexion;
             }
             catch(PDOException $ex)
             {
                                echo "error conexion". $ex->getMessage();
                              
             }
     
     
     }
     
     public  function agregarSusbscriptores($no_contrato,$nombre,$email,$count){
         $conn=$this->getConexion();
         $query=$conn->prepare("INSERT INTO subscriptores(no_contrato,nombre,email) VALUES (:no_contrato,:nombre,:email)");
         $query->bindParam(":no_contrato",$no_contrato);
         $query->bindParam(":nombre",$nombre);
         $query->bindParam(":email",$email);
         $query->execute();
        
         
     }
     
     public  function getSubscriptores(){
         $conn=$this->getConexion();
         $query=$conn->prepare("SELECT* FROM subscriptores");
         $query->execute();
         $res=$query->fetchAll(PDO::FETCH_ASSOC);
         return $res;
     }
     
     public  function getCustomHtml($nombre){
            $html='';

            $html.= "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"; 
            $html.= "<head>\n"; 
            $html.= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"; 
            $html.= "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"; 
            $html.= "<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600' rel='stylesheet' type='text/css'>\n"; 
            $html.= "<head>\n"; 
            $html.= "<!--[if gte mso 12]>\n"; 
            $html.= "> <style type=\"text/css\">\n"; 
            $html.= "> [a.btn {\n"; 
            $html.= "	padding:15px 22px !important;\n"; 
            $html.= "	display:inline-block !important;\n"; 
            $html.= "}]\n"; 
            $html.= "> </style>\n"; 
            $html.= "> <![endif]-->\n"; 
            $html.= "<title>Financiera Ayudamos\n"; 
            $html.= "</title>\n"; 
            $html.= "<style type=\"text/css\">\n"; 
            $html.= "div, p, a, li, td {\n"; 
            $html.= "	-webkit-text-size-adjust:none;\n"; 
            $html.= "}\n"; 
            $html.= ".ReadMsgBody {\n"; 
            $html.= "	width: 100%;\n"; 
            $html.= "	background-color: #d1d1d1;\n"; 
            $html.= "}\n"; 
            $html.= ".ExternalClass {\n"; 
            $html.= "	width: 100%;\n"; 
            $html.= "	background-color: #d1d1d1;\n"; 
            $html.= "	line-height:100%;\n"; 
            $html.= "}\n"; 
            $html.= "body {\n"; 
            $html.= "	width: 100%;\n"; 
            $html.= "	height: 100%;\n"; 
            $html.= "	background-color: #d1d1d1;\n"; 
            $html.= "	margin:0;\n"; 
            $html.= "	padding:0;\n"; 
            $html.= "	-webkit-font-smoothing: antialiased;\n"; 
            $html.= "	-webkit-text-size-adjust:100%;\n"; 
            $html.= "}\n"; 
            $html.= "html {\n"; 
            $html.= "	width: 100%;\n"; 
            $html.= "}\n"; 
            $html.= "img {\n"; 
            $html.= "	-ms-interpolation-mode:bicubic;\n"; 
            $html.= "}\n"; 
            $html.= "table[class=full] {\n"; 
            $html.= "	padding:0 !important;\n"; 
            $html.= "	border:none !important;\n"; 
            $html.= "}\n"; 
            $html.= "table td img[class=imgresponsive] {\n"; 
            $html.= "	width:100% !important;\n"; 
            $html.= "	height:auto !important;\n"; 
            $html.= "	display:block !important;\n"; 
            $html.= "}\n"; 
            $html.= "@media only screen and (max-width: 800px) {\n"; 
            $html.= "body {\n"; 
            $html.= " width:auto!important;\n"; 
            $html.= "}\n"; 
            $html.= "table[class=full] {\n"; 
            $html.= " width:100%!important;\n"; 
            $html.= "}\n"; 
            $html.= "table[class=devicewidth] {\n"; 
            $html.= " width:100% !important;\n"; 
            $html.= " padding-left:20px !important;\n"; 
            $html.= " padding-right: 20px!important;\n"; 
            $html.= "}\n"; 
            $html.= "table td img.responsiveimg {\n"; 
            $html.= " width:100% !important;\n"; 
            $html.= " height:auto !important;\n"; 
            $html.= " display:block !important;\n"; 
            $html.= "}\n"; 
            $html.= "}\n"; 
            $html.= "@media only screen and (max-width: 640px) {\n"; 
            $html.= "table[class=devicewidth] {\n"; 
            $html.= " width:100% !important;\n"; 
            $html.= "}\n"; 
            $html.= "table[class=inner] {\n"; 
            $html.= " width:100%!important;\n"; 
            $html.= " text-align: center!important;\n"; 
            $html.= " clear: both;\n"; 
            $html.= "}\n"; 
            $html.= "table td a[class=top-button] {\n"; 
            $html.= " width:160px !important;\n"; 
            $html.= "  font-size:14px !important;\n"; 
            $html.= " line-height:37px !important;\n"; 
            $html.= "}\n"; 
            $html.= "table td[class=readmore-button] {\n"; 
            $html.= " text-align:center !important;\n"; 
            $html.= "}\n"; 
            $html.= "table td[class=readmore-button] a {\n"; 
            $html.= " float:none !important;\n"; 
            $html.= " display:inline-block !important;\n"; 
            $html.= "}\n"; 
            $html.= ".hide {\n"; 
            $html.= " display:none !important;\n"; 
            $html.= "}\n"; 
            $html.= "table td[class=smallfont] {\n"; 
            $html.= " border:none !important;\n"; 
            $html.= " font-size:26px !important;\n"; 
            $html.= "}\n"; 
            $html.= "table td[class=sidespace] {\n"; 
            $html.= " width:10px !important;\n"; 
            $html.= "}\n"; 
            $html.= "}\n"; 
            $html.= " @media only screen and (max-width: 520px) {\n"; 
            $html.= "}\n"; 
            $html.= "@media only screen and (max-width: 480px) {\n"; 
            $html.= "\n"; 
            $html.= " table {\n"; 
            $html.= " border-collapse: collapse;\n"; 
            $html.= "}\n"; 
            $html.= "table td[class=template-img] img {\n"; 
            $html.= " width:100% !important;\n"; 
            $html.= " display:block !important;\n"; 
            $html.= "}\n"; 
            $html.= "}\n"; 
            $html.= "@media only screen and (max-width: 320px) {\n"; 
            $html.= "}\n"; 
            $html.= "</style>\n"; 
            $html.= "</head>\n"; 
            $html.= "<body>\n"; 
            $html.= "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"full\">\n"; 
            $html.= "  <tr>\n"; 
            $html.= "    <td height=\"54\">&nbsp;</td>\n"; 
            $html.= "  </tr>\n"; 
            $html.= "</table>\n"; 
            $html.= "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"full\">\n"; 
            $html.= "  <tr>\n"; 
            $html.= "    <td align=\"center\"><table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"devicewidth\">\n"; 
            $html.= "        <tr>\n"; 
            $html.= "          <td><table width=\"100%\" bgcolor=\"#ffffff\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"full\" style=\"border-radius:5px 5px 0 0; background-color:#ffffff;\">\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"29\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td><table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\" class=\"inner\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"23\" class=\"hide\">&nbsp;</td>\n"; 
            $html.= "                      <td height=\"75\" class=\"inner\" valign=\"middle\"><a href=\"http://www.financiera-ayudamos.mx/\"><img class=\"logo\" src=\"http://mailing.sistema-siaisa.net/images/logo.png\" width=\"180\" height=\"61\" alt=\"Logo\"></a></td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table>\n"; 
            $html.= "                  <table width=\"150\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\" class=\"inner\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td height=\"15\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td align=\"center\"><a href=\"http://formulario.financiera-ayudamos.mx/\" class=\"top-button\" style=\"font:bold 13px/37px Arial, Helvetica, sans-serif;margin-left: 30; color:#ffffff; text-decoration:none; background:#16c4a9; display: inline-table; border-radius:24px; text-transform:uppercase;width: 120px;\">Me interesa</a></td>\n"; 
            $html.= "                      <td class=\"hide\" width=\"20\">&nbsp;</td>\n"; 
            $html.= "                       <td align=\"center\"><a href=\"#\" class=\"top-button\" style=\"font:bold 13px/37px Arial, Helvetica, sans-serif; color:#ffffff; text-decoration:none; background:#16c4a9; display:block; border-radius:24px; text-transform:uppercase;width: 130px;\">No me interesa</a></td>\n"; 
            $html.= "                      <td class=\"hide\" width=\"20\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td style=\"border-bottom:1px solid #dbdbdb;\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "            </table></td>\n"; 
            $html.= "        </tr>\n"; 
            $html.= "      </table></td>\n"; 
            $html.= "  </tr>\n"; 
            $html.= "</table>\n"; 
            $html.= "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"full\">\n"; 
            $html.= "  <tr>\n"; 
            $html.= "    <td align=\"center\"><table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"devicewidth\">\n"; 
            $html.= "        <tr>\n"; 
            $html.= "          <td><table width=\"100%\" bgcolor=\"#ffffff\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"full\" style=\"background-color:#ffffff;\">\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"23\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"id=\"main\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                      <td><table width=\"76%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"inner\" id=\"banner\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td style=\"font:bold 27px Arial, Helvetica, sans-serif; border-right:1px solid #dbdbdb;\" class=\"smallfont\">¡Empiece a formar un Historial Crediticio con Nosotros!</td>\n"; 
            $html.= "                            \n"; 
            $html.= "\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                        </table>\n"; 
            $html.= "                        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"id=\"main\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                      <td><table width=\"76%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"inner\" id=\"banner\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                           \n"; 
            $html.= "                            \n"; 
            $html.= "\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                        </table>\n"; 
            $html.= "                        <table width=\"22%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\" class=\"inner\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td align=\"center\"><a href=\"https://www.facebook.com/Financiera-Ayudamos-809341039179435/\" style=\"margin-top:5px; display:inline-block;\"><img src=\"http://mailing.sistema-siaisa.net/images/facebook.png\" width=\"32\" height=\"atuo\" alt=\"Social Media\" /></a></td>\n"; 
            $html.= "                            <td align=\"center\"><a href=\"#\" style=\"margin-top:5px; display:inline-block;\"><img src=\"http://mailing.sistema-siaisa.net/images/twitter.png\" width=\"32\" height=\"atuo\" alt=\"Social Media\" /></a></td>\n"; 
            $html.= "                            <td align=\"center\"><a href=\"#\" style=\"margin-top:5px; display:inline-block;\"><img src=\"http://mailing.sistema-siaisa.net/images/google.png\" width=\"32\" height=\"atuo\" alt=\"Social Media\" /></a></td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                            <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                            <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                        </table></td>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table>\n"; 
            $html.= "                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"3.33%\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                      <td width=\"93.33%\"><img class=\"imgresponsive\" src=\"http://mailing.sistema-siaisa.net/images/banner.jpg\" width=\"554\" height=\"atuo\" alt=\"Banner\" /></td>\n"; 
            $html.= "                      <td width=\"3.33%\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                      <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                      <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table>\n"; 
            $html.= "                  <table width=\"50%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td style=\"font:bold 27px Arial, Helvetica, sans-serif; border-right:1px solid #dbdbdb;\" class=\"smallfont\">Tienes un Préstamo Preaprobado* por:</td>\n"; 
            $html.= "                            <td style=\"font:300 22px 'Open Sans', Arial, Helvetica, sans-serif; color:#333332;float:center;\" class=\"smallfont\">$32,500.00 \n"; 
            $html.= " </td>\n"; 
            $html.= "                           \n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            \n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                        </table>\n"; 
            $html.= "                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                      <td><table width=\"50%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\" class=\"inner\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "\n"; 
            $html.= " <td style=\"font:14px/19px Arial, Helvetica, sans-serif; color:#333332;float:left;\">Para contratar solo tienes que llamarnos y mencionar el siguiente  folio:</td>\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "                            \n"; 
            $html.= "                           \n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          \n"; 
            $html.= "                        </table><table width=\"50%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\" class=\"inner\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "\n"; 
            $html.= "<td align=\"left\" class=\"readmore-button\"><a style=\"font:bold 12px/29px Arial, Helvetica, sans-serif; color:#ffffff; text-decoration:none; background:#16c4a9; float:left; padding:0 19px; border-radius:24px; text-transform:uppercase;\">15270\n"; 
            $html.= "</a></td>\n"; 
            $html.= "\n"; 
            $html.= "                            \n"; 
            $html.= "                           \n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          \n"; 
            $html.= "                        </table>\n"; 
            $html.= "                        <table width=\"50%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\" class=\"inner\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            \n"; 
            $html.= "                            <td class=\"hide\" width=\"23\">&nbsp;</td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "                            <td class=\"hide\" height=\"20\">&nbsp;</td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                        </table>\n"; 
            $html.= "                        </td>\n"; 
            $html.= "\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td height=\"16\">&nbsp;</td>\n"; 
            $html.= "                      <td height=\"16\">&nbsp;</td>\n"; 
            $html.= "                      <td height=\"16\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td style=\"border-bottom:1px solid #dbdbdb;\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "            </table></td>\n"; 
            $html.= "        </tr>\n"; 
            $html.= "      </table></td>\n"; 
            $html.= "  </tr>\n"; 
            $html.= "</table>\n"; 
            $html.= "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"full\">\n"; 
            $html.= "  <tr>\n"; 
            $html.= "    <td align=\"center\"><table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"devicewidth\">\n"; 
            $html.= "        <tr>\n"; 
            $html.= "          <td><table width=\"100%\" bgcolor=\"#313131\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"full\" style=\" background-image:url(http://mailing.sistema-siaisa.net/images/white-bg.gif); background-repeat:repeat-x; background-position:left top;\">\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"23\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td align=\"center\"><img src=\"http://mailing.sistema-siaisa.net/images/picture.png\" width=\"83\" height=\"atuo\" alt=\"picture\" /></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"23\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "               \n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"16\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"40%\" height=\"2\"></td>\n"; 
            $html.= "                      <td width=\"10%\" height=\"2\" style=\" border-bottom:2px solid #ffffff;\"></td>\n"; 
            $html.= "                      <td width=\"40%\" height=\"2\"></td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"16\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td align=\"center\" style=\"font:700 27px 'Open Sans', Arial, Helvetica, sans-serif; color:#ffffff;\" class=\"smallfont\"><h6 style=\"\n"; 
            $html.= "    margin-top: 10px;\n"; 
            $html.= "    margin-bottom: 10px;\n"; 
            $html.= "\">Tel. 55-99-15-67</h6>\n"; 
            $html.= "<h6 style=\"\n"; 
            $html.= "    margin-top: 10px;\n"; 
            $html.= "    margin-bottom: 10px;\n"; 
            $html.= "\">Lunes a Viernes  de 9:00 a 18:00</h6>\n"; 
            $html.= "<h6 style=\"\n"; 
            $html.= "    margin-top: 10px;\n"; 
            $html.= "    margin-bottom: 10px;\n"; 
            $html.= "\">Sábado de 9:00 a 16:00</h6>\n"; 
            $html.= "<h6 style=\"\n"; 
            $html.= "    margin-top: 10px;\n"; 
            $html.= "    margin-bottom: 10px;\n"; 
            $html.= "\">¡Acércate a un ejecutivo!</h6>\n"; 
            $html.= "<h6 style=\"\n"; 
            $html.= "    margin-top: 10px;\n"; 
            $html.= "    margin-bottom: 10px;\n"; 
            $html.= "\">Tienes hasta el 5 de Junio de 2015 para contratar</h6></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"16\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td>&nbsp;</td>\n"; 
            $html.= "                      <td align=\"center\" class=\"template-img\"></td>\n"; 
            $html.= "                      <td>&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"25\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                      <td align=\"center\" style=\"font:15px/19px Arial, Helvetica, sans-serif; color:#ffffff;width: 350px; padding-right: 15px;padding-left: 15px;\">Vigencia para contratar el crédito del 24 de abril de 2015 al 05 de junio de 2015\n"; 
            $html.= "Comisión por apertura: 9% (nueve por ciento)\n"; 
            $html.= "Tasa fija: 49.2% anual (cuarenta y nueve punto dos por ciento)\n"; 
            $html.= "Moneda Nacional ( Pesos mexicanos) \n"; 
            $html.= "* Aplican restricciones. Sujeto a buen historial crediticio y a capacidad de pago.\n"; 
            $html.= "</td><td align=\"center\" style=\"font:15px/19px Arial, Helvetica, sans-serif; color:#ffffff;\"><h2>CAT: 124.71%</h2>\n"; 
            $html.= "Sin IVA. Informativo. Fecha de cálculo: 23 de abril del 2015\n"; 
            $html.= "\n"; 
            $html.= "\n"; 
            $html.= "</td>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                      <td align=\"center\" style=\"font:15px/19px Arial, Helvetica, sans-serif; color:#ffffff;padding-top: 50px;\">Financiera Ayudamos, S.A. de C.V. SOFOM ER, Av. Canal de Miramontes 2600, Colonia Avante,  Delegación  Coyoacán, 04460, DF,  recaba sus datos para verificar su identidad.\n"; 
            $html.= "El Aviso de Privacidad Integral actualizado se encuentra a su disposición en cualquiera  de nuestras sucursales y en la página http://www.financiera-ayudamos.mx\n"; 
            $html.= "Consulta los requisitos de contratación, términos y condiciones en: http://www.financiera-ayudamos.mx\n"; 
            $html.= "\n"; 
            $html.= "</td>\n"; 
            $html.= "                      <td width=\"23\" class=\"sidespace\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"25\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td align=\"center\" class=\"readmore-button\"><a href=\"http://www.financiera-ayudamos.mx/docs/AV.pdf\" style=\"font:bold 12px/29px Arial, Helvetica, sans-serif; color:#16c4a9; text-decoration:none; background:#ffffff; display:inline-block; padding:0 19px; border-radius:24px; text-transform:uppercase;\">Aviso de privacidad.</a></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"16\"></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td>&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "            </table></td>\n"; 
            $html.= "        </tr>\n"; 
            $html.= "      </table></td>\n"; 
            $html.= "  </tr>\n"; 
            $html.= "</table>\n"; 
            $html.= "\n"; 
            $html.= "<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"full\">\n"; 
            $html.= "  <tr>\n"; 
            $html.= "    <td align=\"center\"><table width=\"600\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"devicewidth\">\n"; 
            $html.= "        <tr>\n"; 
            $html.= "          <td><table width=\"100%\" bgcolor=\"#ffffff\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"full\" style=\"border-radius:0 0 7px 7px;\">\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td height=\"18\">&nbsp;</td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "              <tr>\n"; 
            $html.= "                <td><table class=\"inner\" align=\"right\" width=\"340\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; text-align:center;\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"21\">&nbsp;</td>\n"; 
            $html.= "                      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" class=\"full\">\n"; 
            $html.= "                                <tr>\n"; 
            $html.= "                                  <td align=\"center\" style=\"font:11px Helvetica,  Arial, sans-serif; color:#ffffff;\"><a style=\"color:#000000; text-decoration:none;\" href=\"#\"> </a></td>\n"; 
            $html.= "                                  <td style=\"color:#000000;\"> | </td>\n"; 
            $html.= "                                  <td align=\"center\" style=\"font:11px Helvetica,  Arial, sans-serif; color:#ffffff;\"><a style=\"color:#000000; text-decoration:none;\" href=\"#\"> cancelar suscripción</a></td>\n"; 
            $html.= "                                  <td style=\"color:#000000;\"> | </td>\n"; 
            $html.= "                                  <td align=\"center\" style=\"font:11px Helvetica,  Arial, sans-serif; color:#ffffff;\"><a style=\"color:#000000; text-decoration:none;\" href=\"#\"> Enviar a un amigo.</a></td>\n"; 
            $html.= "                                  <td class=\"hide\" width=\"40\" align=\"right\">&nbsp;</td>\n"; 
            $html.= "                                </tr>\n"; 
            $html.= "                                <tr>\n"; 
            $html.= "                                  <td height=\"18\">&nbsp;</td>\n"; 
            $html.= "                                </tr>\n"; 
            $html.= "                              </table></td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                        </table></td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table>\n"; 
            $html.= "                  <table class=\"inner\" align=\"left\" width=\"230\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; text-align:center;\">\n"; 
            $html.= "                    <tr>\n"; 
            $html.= "                      <td width=\"21\">&nbsp;</td>\n"; 
            $html.= "                      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td align=\"center\" style=\"font:11px Helvetica,  Arial, sans-serif; color:#000000;\">&copy; 2016, Todos los derchos Reservados </td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                          <tr>\n"; 
            $html.= "                            <td height=\"18\">&nbsp;</td>\n"; 
            $html.= "                          </tr>\n"; 
            $html.= "                        </table></td>\n"; 
            $html.= "                      <td width=\"21\">&nbsp;</td>\n"; 
            $html.= "                    </tr>\n"; 
            $html.= "                  </table></td>\n"; 
            $html.= "              </tr>\n"; 
            $html.= "            </table></td>\n"; 
            $html.= "        </tr>\n"; 
            $html.= "        <tr>\n"; 
            $html.= "          <td height=\"20\">&nbsp;</td>\n"; 
            $html.= "        </tr>\n"; 
            $html.= "      </table></td>\n"; 
            $html.= "  </tr>\n"; 
            $html.= "</table>\n"; 
            $html.= "</body>\n"; 
            $html.= "</html>\n";
            return $html;
     }
         
     
     
     
}
